workflows:
  android-compose:
    name: Android Compose Build
    environment:
      java: 17

    scripts:
      - name: Build APK
        script: ./gradlew assembleDebug

    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk